### ISSUE TITLE
Task Module

### ISSUE THREAD

**Issue by aravindramvjs** [fssa-batch3/sec_c_sec_c_aravind.venkedeshwaran__corejava_project_2#1]
# Task Module: 

## Task Object
- [x] Create Task Object

### Validator: 
- [x] Validate TaskName
- [x] validate TaskDescription
- [x] validate Due Date
- [x] validate Task Notes
- [x] validate Reminder
- [x] validate Created Date
- [x] validate Created Time

### Test Case: 
- [x] Test Task Name validator
- [x] Test TaskDescription validator
- [x] Test Due Date validator
- [x] Test Task Notes validator
- [x] Test Reminder validator
- [x] Test Created Date validator
- [x] Test Created Time validator

### Task:
- [x] Create Task
- [x] Read All Task
- [x] Update Task Name, Description, Due Date, Priority, Status, Notes, Reminder
- [x] Delete Task

### Task Tags: 
- [x] Create Tag
- [x] Read Tag
- [x] Update Tag Name
- [x] Delete Tag

### Task Sub Task:
- [x] Create Sub Task
- [x] Read Sub Task
- [x] Update Sub Task Name
- [x] Delete Sub Task

### Task: 

- [x] Add Task Service
- [x] Read Task Service
- [x] Delete Task Service
- [x] Update Task Service (Use Switch case to switch between editable task attributes)

### Task Tags: 

- [x] Add Task Tag Service
- [x] Read Task Tag Service
- [x] Delete Task Tag Service
- [x] Update Tag Task Service

### Task Sub Task: 

- [x] Add Sub Task Service
- [x] Read Sub Task Service
- [x] Delete Sub Task Service
- [x] Update Sub Task Service

## Test Case:

- [x] Test Add Task Service
- [x] Test Read Task Service
- [x] Test Delete Task Service
- [x] Test Update Task Service

- [x] Test Add Task Tag Service
- [x] Test Read Task Tag Service
- [x] Test Delete Task Tag Service
- [x] Test Update Tag Task Service

- [x] Test Add Sub Task Service
- [x] Test Read Sub Task Service
- [x] Test Delete Sub Task Service
- [x] Test Update Sub Task Service

# Progress DAO: 

- [x] Change Task Status
- [x] Insert Daily Progress Data while changing the task status
- [x] Weekly Progress Data while changing the task status
- [x] Overall Progress Data while changing the task status

## Actual => 40 hrs.
