### ISSUE TITLE
Task Module | Simplify adding task

### ISSUE THREAD

**Issue by aravindramvjs** [fssa-batch3/sec_c_sec_c_aravind.venkedeshwaran__corejava_project_2#10]
### Task Module | Simplify adding task

- [ ] change the design of adding task by not filling the entire form instead just type task name and add task
- [ ] change the task popup design
- [ ] change the addtask dao to only add task name in db
- [ ] change the update task dao to handle nullable attributes. 
- [ ] modify the service layer accordingly
